### ISSUE TITLE
A text to speech converter.

### ISSUE THREAD

**Issue by nisha331** [LetsGrowMoreCommunity/WebDev-Playyard#12]
## Checks 
[ ] Project uses HTML , CSS , JS
[ ] Project can be hosted on GitHub 

## **Describe the Project**
A webapp using HTML CSS and javascript that converts speech to text.

**Comment by nisha331** [comment]
Kindly assign this issue to me.

**Comment by jyothi-k-g** [comment]
@rohan-kulkarni-25  please assign this issue to me under LGMSOC21

**Comment by rohan-kulkarni-25** [comment]
@nisha331  Go for it makes a new folder with the app name and follow the  project structure

**Comment by nisha331** [comment]
Hey @rohan-kulkarni-25 I am a bit perplexed , i only have a html file and a css file in the project,  where to place it?  I actually cannot get the readme. It would be great of you if you could explain the project structure in brief here. Sorry for the inconvenience.

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Hey @rohan-kulkarni-25 I am a bit perplexed , i only have a html file and a css file in the project, where to place it? I actually cannot get the readme. It would be great of you if you could explain the project structure in brief here. Sorry for the inconvenience.

Keep Html files in root & css files in assets -> css folder -> css file
