### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by soma2000-lang** [LetsGrowMoreCommunity/WebDev-Playyard#13]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- **Sudoku Solver**
![WhatsApp Image 2021-07-21 at 22 41 36 (1)](https://user-images.githubusercontent.com/56045049/126589176-4ad828db-bfb4-4b06-b675-8beb96b41150.jpeg)

The project is done using html ,javascript and css using the concept of backtracking

Stack:
[x] Html
[x] CSS
[x] JavaScript

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by soma2000-lang** [comment]
@rohan-kulkarni-25 @ujju20  Please assign this issue to me.I am an LGM-SOC 21participant

**Comment by rohan-kulkarni-25** [comment]
@soma2000-lang  Go for it and do follow project structure

**Comment by soma2000-lang** [comment]
@rohan-kulkarni-25 @SnehaAgarwal361  can u plz give it a tag like level 1 ,2 ,3 or 4
