### ISSUE TITLE
Memory Card Game

### ISSUE THREAD

**Issue by palaksinghania05** [LetsGrowMoreCommunity/WebDev-Playyard#14]
## Checks 
[✔] Project uses HTML , CSS , JS
[✔] Project can be hosted on GitHub 

## **Describe the Project**

- A basic memory card game that tests user memory by remembering where the cards actually are.

## **Screenshots**

- Screenshots are there in the README.md of my project,

**Comment by palaksinghania05** [comment]
Please assign this issue to me.

**Comment by rohan-kulkarni-25** [comment]
Yes @palaksinghania05  GO for it and do follow structure of project

**Comment by palaksinghania05** [comment]
I want to clarify that:
1. I have to make a folder of my project under Projects folder.
2. Then have to create three sub folders : Assets, Pages, Media.
3. Put css file in Assets, HTML and JS file in Pages, images and screenshots in Media.
4. Add a readme file.
5. Then create pull request.

If anything left, please mention.

**Comment by rohan-kulkarni-25** [comment]
Hey @palaksinghania05 
In the project folder, I have created one folder in that I have created a structure you can refer it !

**Comment by palaksinghania05** [comment]
@rohan-kulkarni-25 Okay I got it now. But my project have just one html file and no index.html separately. So what should I do?

**Comment by rohan-kulkarni-25** [comment]
OK No problem @palaksinghania05
