### ISSUE TITLE
Form tag in html.

### ISSUE THREAD

**Issue by siddhi-244** [LetsGrowMoreCommunity/WebDev-Playyard#17]
## Which Topic Notes will you like to add 
[x] HTML
[ ] CSS
[ ] JS

## **Describe the Topic **
- Would like to add notes for Form tag in html.

**Comment by rohan-kulkarni-25** [comment]
Go for it @siddhi-244 !

**Comment by gunjan-g** [comment]
@Sanskriti2401 can i work on this issue if nobody's working

**Comment by Sanskriti2401** [comment]
Ya, it's been 19 days, there is still no PR.
@gunjan-g I will assign you but make your PR before 11pm today, neither it will not be counted.

**Comment by gunjan-g** [comment]
> Ya, it's been 19 days, there is still no PR.
> @gunjan-g I will assign you but make your PR before 11pm today, neither it will not be counted.

Yes, I'll take care of that. Thanks.
