### ISSUE TITLE
Youtube UI Clone

### ISSUE THREAD

**Issue by mrkc2303** [LetsGrowMoreCommunity/WebDev-Playyard#18]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

I would be making a clone of YouTube UI using HTML, CSS. The website will be fully responsive and mobile friendly too.

**Comment by mrkc2303** [comment]
Kindly Assign me this issue!

**Comment by rohan-kulkarni-25** [comment]
Go for it @mrkc2303
