### ISSUE TITLE
Quote Generator

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#19]
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**

 Quote Generator randomly displays a quote when a button is clicked by user.

**Comment by khushi-purwar** [comment]
Can I work on this issue?

**Comment by rohan-kulkarni-25** [comment]
Go for it @khushi-purwar
