### ISSUE TITLE
Weather Application Using API

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#23]
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**

A simple API enabled website build using HTML, CSS & JavaScript.
Weather app will show the following information, the user's city and country, day and date , the temperature value (21°C) in Celsius unit, the weather description (rainy), an Icon that shows the weather status, and then min and max temperature.

## **Screenshots**

<img src="https://github.com/khushi-purwar/Weather-Application-using-API/raw/master/ss.png" />

**Comment by khushi-purwar** [comment]
Can I add this project ?

**Comment by rohan-kulkarni-25** [comment]
Go for it @khushi-purwar
