### ISSUE TITLE
Tic Tac Toe Game in JS

### ISSUE THREAD

**Issue by Ayonijakaushik19** [LetsGrowMoreCommunity/WebDev-Playyard#25]
I want to add a new project of Tic Tac Toe Game in JavaScript.
Hi, @SnehaAgarwal361 Please assign this to me.

**Comment by SnehaAgarwal361** [comment]
Yes go for it please take care of the contribution guidelines and do not forget to add a short video and ss of your work.
Happy coding:)

**Comment by gunjan-g** [comment]
@Sanskriti2401 can I work on this issue if anyone's not working

**Comment by SnehaAgarwal361** [comment]
Hey @gunjan-g we already now have this project repo.
thankyou.
you can however add any other projects of your choice:)
