### ISSUE TITLE
Calculator App

### ISSUE THREAD

**Issue by anushruti11** [LetsGrowMoreCommunity/WebDev-Playyard#30]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- A simple calculator with the basic functions..

## **Screenshots**

![image](https://user-images.githubusercontent.com/65386044/126796415-da5d88ac-4884-4ca8-b37b-b7641cb62092.png)

**Comment by rohan-kulkarni-25** [comment]
Go for it @anushruti11
