### ISSUE TITLE
COMPOUND INTEREST CALCULATOR

### ISSUE THREAD

**Issue by mrkc2303** [LetsGrowMoreCommunity/WebDev-Playyard#31]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

This is a basic project which calculate Compound Interest by entering some details.

**Comment by mrkc2303** [comment]
Kindly assign me this issue under LGMSOC'21

**Comment by rohan-kulkarni-25** [comment]
go for it @mrkc2303
