### ISSUE TITLE
Gradient Background Generator

### ISSUE THREAD

**Issue by mrkc2303** [LetsGrowMoreCommunity/WebDev-Playyard#32]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- A simple Gradient Background Generator, by selecting two colors, using JS it will make a gradient using those colors and provide you the code for it so that you can use it on your website.

**Comment by mrkc2303** [comment]
Kindly assign me this issue under LGMSOC'21.

**Comment by Sanskriti2401** [comment]
@mrkc2303 Yes go for it and take care of the contribution guidelines. Do not forget to add ss or demo video of your project.
Good luck :)
