### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by Atif0604** [LetsGrowMoreCommunity/WebDev-Playyard#34]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- Weather App using open weather api

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by Sanskriti2401** [comment]
@Atif0604 Yes go for it and take care of the contribution guidelines. Do not forget to add ss or demo video of your project.
Good luck :)
