### ISSUE TITLE
TO-DO LIST APP

### ISSUE THREAD

**Issue by jainapoorva40** [LetsGrowMoreCommunity/WebDev-Playyard#38]
## Checks 
[✔] Project uses HTML , CSS , JS
[✔] Project can be hosted on GitHub

## **Describe the Project**
A basic TO-DO LIST app that enables storing ,deleting and filtering of the tasks.

**Comment by jainapoorva40** [comment]
Please assign this issue to me under LGM-SOC.

**Comment by Sanskriti2401** [comment]
@jainapoorva40  Go for it and take care of the contribution guidelines. Do not forget to add ss or demo video of your project.
Good luck :)
