### ISSUE TITLE
Covid Tracker App

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#39]
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**

Beginner friendly project which uses basics API's and provide real time data of corona cases (Recovered, deaths, active cases) with some latest covid news.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by khushi-purwar** [comment]
Please assign me this issue under LGMSOC?

**Comment by Sanskriti2401** [comment]
@khushi-purwar Go for it and take care of the contribution guidelines. Do not forget to add ss or demo video of your project.
Good luck :)
