### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by Atif0604** [LetsGrowMoreCommunity/WebDev-Playyard#42]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- Add a snake game

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by Harshil-Jani** [comment]
Can I have an attempt over it?

**Comment by Atif0604** [comment]
> Can I have an attempt over it?

Sorry @Harshil-Jani this issue is created by me and not the project admins

**Comment by Atif0604** [comment]
hey @Sanskriti2401 @SnehaAgarwal361   can you assign it to me

**Comment by SnehaAgarwal361** [comment]
Yes, go ahead.
Please take care of contribution guidelines ad happy coding:)
