### ISSUE TITLE
maths quiz game

### ISSUE THREAD

**Issue by nisha331** [LetsGrowMoreCommunity/WebDev-Playyard#43]
## Checks 

  Project uses HTML , CSS , JS
 Project can be hosted on GitHub 

Game for kids to practice addition.

**Comment by nisha331** [comment]
I would like to work on the issue kindly assign it to me.

**Comment by Sanskriti2401** [comment]
@nisha331 Go for it!!  Take care of the contribution guidelines and project structure.
Good luck :)
