### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#46]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**
BMI is Body Mass Index. This calculator will take height and and weight of a person and will give the value of BMI.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by khushi-purwar** [comment]
> ## Checks
> [x] Project uses HTML , CSS , JS
> [x] Project can be hosted on GitHub
> 
> ## **Describe the Project**
> BMI is Body Mass Index. This calculator will take height and and weight of a person and will give the value of BMI.
> 
> ## **Screenshots**
> * If applicable, add screenshots to help explain your project.

Can i work on this project under LGMSOC?

**Comment by Sanskriti2401** [comment]
@khushi-purwar Go for it!! Take care of the contribution guidelines and project structure.
Good luck :)
