### ISSUE TITLE
Tip Calculator

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#48]
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**

A tip calculator is a calculator that calculates a tip based on the total bill.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by khushi-purwar** [comment]
Can i work on this project?

**Comment by Sanskriti2401** [comment]
@khushi-purwar Go for it!! Take care of the contribution guidelines and project structure.
Good luck :)
