### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by swathi-469** [LetsGrowMoreCommunity/WebDev-Playyard#5]
Hi I would to add Contribution guidelines in the folder . Please assign this to me

**Comment by rohan-kulkarni-25** [comment]
Yes !! @swathi-469  I have created a file in which you can add contribution please include basic steps required for setting up project also in that

**Comment by swathi-469** [comment]
Thanks for assigning

**Comment by Ayonijakaushik19** [comment]
Hi, @rohan-kulkarni-25 I have made a PR for this issue please have a look.

**Comment by swathi-469** [comment]
But sir you have assigned me but how others can work and make a pull request with assigning

**Comment by swathi-469** [comment]
But sir you have assigned me but how others can work and make a pull request with assigning

**Comment by rohan-kulkarni-25** [comment]
@swathi-469  Your PR will be considered

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Hi, @rohan-kulkarni-25 I have made a PR for this issue please have a look.

Please work on issues assigned as this will waste your efforts

**Comment by swathi-469** [comment]
Ok sir I will do it immediately and make my pull request

**Comment by swathi-469** [comment]
I have made a PR for this issue please have a look.
