### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#50]
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**
A simple web application which will generate a QR Code.

## **Screenshots**

<img src="https://user-images.githubusercontent.com/52875298/127135385-7e7f9488-b81c-4385-9edf-7fc93e5ed9bc.png" />

**Comment by khushi-purwar** [comment]
Can i add this project under LGMSOC?

**Comment by Sanskriti2401** [comment]
@khushi-purwar Go for it!! Take care of the contribution guidelines.
Good luck :)
