### ISSUE TITLE
Tictactoe Game

### ISSUE THREAD

**Issue by Atif0604** [LetsGrowMoreCommunity/WebDev-Playyard#57]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- A Tictactoe Game 

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by Atif0604** [comment]
hey @Sanskriti2401 
please assign it to me

**Comment by Sanskriti2401** [comment]
@Atif0604 Yes, go ahead. Take care of project structure.
Good Luck :)
