### ISSUE TITLE
Tindog- Tinder for Dogs

### ISSUE THREAD

**Issue by gunjan-g** [LetsGrowMoreCommunity/WebDev-Playyard#58]
## Checks 

- [x]  Project uses HTML , CSS , Bootstrap
- [x] Project can be hosted on GitHub 

## **Describe the Project**
This project is a beginner friendly project which uses HTML , CSS and Bootstrap to build up this entire beautiful website. This is a tinder website designed especially for dogs.

## **Screenshots**
![image](https://user-images.githubusercontent.com/81305824/127783093-0abc32a7-ed07-43b1-86c3-7b321ac8ab68.png)

**Comment by gunjan-g** [comment]
@Sanskriti2401 please assign this issue to me under LGMSOC

**Comment by Sanskriti2401** [comment]
@gunjan-g Yes, go ahead.  Your idea sounds great and interesting. Take care of project structure and contribution guidelines.
Good Luck :)

**Comment by gunjan-g** [comment]
> @gunjan-g Yes, go ahead. Your idea sounds great and interesting. Take care of project structure and contribution guidelines.
> Good Luck :)

Thank you 😄

**Comment by Ruheej1** [comment]
Hey! Please assign me this issue
