### ISSUE TITLE
Netflix UI Clone

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#60]
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**
Building a Netflix UI clone. The website will be fully responsive and mobile friendly too.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by khushi-purwar** [comment]
Can I add this project ?

**Comment by Sanskriti2401** [comment]
@khushi-purwar Yes, go ahead. Take care of contribution guidelines.
Good luck :)
