### ISSUE TITLE
Add some badges to the README

### ISSUE THREAD

**Issue by Umesh-01** [LetsGrowMoreCommunity/WebDev-Playyard#62]
### Description
Add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

### Solution
I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

- [ ] Will add some more badges
- [ ] Will align them to center
- [ ] Will link them to related webpages/sections

### Sample Screenshot

![image](https://user-images.githubusercontent.com/83420185/128059721-91552cc4-9120-4c46-ae2f-94eb7c397ff5.png)

**Comment by Sanskriti2401** [comment]
@Umesh-01 Yes, go ahead. Good luck
