### ISSUE TITLE
Custom Range Slider

### ISSUE THREAD

**Issue by Atif0604** [LetsGrowMoreCommunity/WebDev-Playyard#63]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- A clear and concise description of what the Project is.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by Atif0604** [comment]
hey @Sanskriti2401 please assign me

**Comment by Sanskriti2401** [comment]
@Atif0604 Yes, go ahead!
