### ISSUE TITLE
The Drum Kit 

### ISSUE THREAD

**Issue by Ruheej1** [LetsGrowMoreCommunity/WebDev-Playyard#64]
## Checks 

[ :heavy_check_mark:] Project uses HTML , CSS , JS

[ :heavy_check_mark:] Project can be hosted on GitHub 

## **Describe the Project**

- It is a beginner friendly website which can be created using HTML, CSS and Javascript. The idea is to play sounds when user touches the buttons available on the website

## **Screenshots**

![Untitled (2)](https://user-images.githubusercontent.com/59756474/128142331-50d575a7-d5d5-47c4-b110-168b3bca0cf1.png)

**Comment by Ruheej1** [comment]
Please Assign me this issue under LGMSOC'21

**Comment by Sanskriti2401** [comment]
@Ruheej1 Yes, go ahead. Take care of contribution guidelines.
Good luck :)
