### ISSUE TITLE
The Dice Game

### ISSUE THREAD

**Issue by Ruheej1** [LetsGrowMoreCommunity/WebDev-Playyard#65]
## Checks 
[  :heavy_check_mark: ] Project uses HTML , CSS , JS
[  :heavy_check_mark: ] Project can be hosted on GitHub 

## **Describe the Project**

- It is a simple website created using HTML,CSS and Javascript. Here, user can play a dice game and the dices shown on the page will show a different number each time, and the player with larger number will win. The result will be shown above. 

## **Screenshots**

![Untitled (3)](https://user-images.githubusercontent.com/59756474/128145557-1656ea25-09e9-4a29-81c9-9c9a6f441176.png)

**Comment by Ruheej1** [comment]
Can I add this? if Yes, please assign this to me under LGMSOC'21

**Comment by Sanskriti2401** [comment]
@Ruheej1 Yes, go ahead. Take care of contribution guidelines.
Good luck :)
