### ISSUE TITLE
Simon Game

### ISSUE THREAD

**Issue by Ruheej1** [LetsGrowMoreCommunity/WebDev-Playyard#66]
## Checks 
[ &check;] Project uses HTML , CSS , JS
[ &check;] Project can be hosted on GitHub 

## **Describe the Project**

- A simple game which can be played by user by following the color press indicated at each level. It is created using HTML,CSS & JavaScript. Also, the cool feature is that every mouse click creates a different sound according to the color.

**Comment by Ruheej1** [comment]
Can I add this? If yes, Please assign this to me under LGMSOC'21

**Comment by Sanskriti2401** [comment]
@Ruheej1 Yes, go ahead. Take care of contribution guidelines.
Good luck :)
