### ISSUE TITLE
Coin Toss App

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#68]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

This app will simulates a coin flip which will produce head and tails with a cool animation. It also maintains the count of heads and tails. We can also reset the count of heads and tails using reset button.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by khushi-purwar** [comment]
I want to work on this project. Please assign me.

**Comment by Sanskriti2401** [comment]
@khushi-purwar Yes, go ahead. Take care of contribution guidelines.
Good luck :)
