### ISSUE TITLE
Lets practice

### ISSUE THREAD

**Issue by nisha331** [LetsGrowMoreCommunity/WebDev-Playyard#70]
## Checks 
[ ] Project uses HTML , CSS , JS
[ ] Project can be hosted on GitHub 

## **Describe the Project**
This webapp is basically for kids to practice addition, substraction, multiplication and division.
## **Screenshots**
![pr](https://user-images.githubusercontent.com/76838660/128412158-18e9adc0-c815-4cec-855f-9b44fb74eb30.PNG)
![d](https://user-images.githubusercontent.com/76838660/128412166-c3ae0f92-4cf4-42f0-809a-9a5d59a022ec.PNG)

**Comment by nisha331** [comment]
I would like to work on this issue kindly assign it to me

**Comment by Sanskriti2401** [comment]
@nisha331 Yes, go ahead. Take care of contribution guidelines.
Good luck :)
