### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#72]
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**

Creating a password generator  using JavaScript. In this, we can choose the length of a password with different multiple options. and also copy the password to clipboard.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by khushi-purwar** [comment]
I want to work on this project. Please assign me.

**Comment by Sanskriti2401** [comment]
@khushi-purwar Yes, go ahead. Take care of contribution guidelines.
Good luck :)
