### ISSUE TITLE
Double Vertical Slider

### ISSUE THREAD

**Issue by Atif0604** [LetsGrowMoreCommunity/WebDev-Playyard#76]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- Add Double Vertical Slider

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by Atif0604** [comment]
Hey @Sanskriti2401 please assign

**Comment by Sanskriti2401** [comment]
@Atif0604 Yes, go ahead. Take care of contribution guidelines.
Good luck :)
