### ISSUE TITLE
Media Queries- CSS Docs

### ISSUE THREAD

**Issue by gunjan-g** [LetsGrowMoreCommunity/WebDev-Playyard#78]
## Which Topic Notes will you like to add 

- [x] CSS

## **Describe the Topic **
Media Queries in CSS

**Comment by gunjan-g** [comment]
@Sanskriti2401 please assign this issue to me

**Comment by Sanskriti2401** [comment]
@gunjan-g Yes, go ahead. Take care of project structure.
Good luck :)
