### ISSUE TITLE
Joke Speaking Robot

### ISSUE THREAD

**Issue by khushi-purwar** [LetsGrowMoreCommunity/WebDev-Playyard#81]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

Joke telling robot web app using javascript

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by khushi-purwar** [comment]
Please assign me this last issue for LGMSOC21.

**Comment by Sanskriti2401** [comment]
@khushi-purwar Yes, go ahead. Take care of contribution guidelines.
Good luck :)
