### ISSUE TITLE
Music App

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [LetsGrowMoreCommunity/WebDev-Playyard#82]
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**
You just need to tap once and music will start.This project is made by Javascript.

- A clear and concise description of what the Project is.
This is a music app. One tap,one music.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

**Comment by Sanskriti2401** [comment]
@Sulagna-Dutta-Roy Yes, go ahead. Take care of contribution guidelines.
Good luck :)
