### ISSUE TITLE
CSS Positioning- Relative, Fixed, Static

### ISSUE THREAD

**Issue by gunjan-g** [LetsGrowMoreCommunity/WebDev-Playyard#85]
## Which Topic Notes will you like to add 
- [x] CSS

##  Describe the Topic 
Notes for positioning in CSS- relative, absolute and fixed

**Comment by gunjan-g** [comment]
@Sanskriti2401 please assign this issue to me under LGMSOC

**Comment by gunjan-g** [comment]
@Sanskriti2401 please assign this issue to me under LGMSOC

**Comment by Sanskriti2401** [comment]
@gunjan-g Yes, go ahead. Take care of contribution guidelines.
Good luck :)
