### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by palaksinghania05** [LetsGrowMoreCommunity/WebDev-Playyard#89]
## Checks 
[Yes] Project uses HTML , CSS , JS
[Yes] Project can be hosted on GitHub 

## **Describe the Project**

- Very famous hangman game using javascript. Users have to guess the word with clues and hints before a hangman is formed due to their wrong choices.

## **Screenshots**

- Included in the project itself.

**Comment by palaksinghania05** [comment]
@rohan-kulkarni-25  
Please assign this issue to me.

**Comment by SnehaAgarwal361** [comment]
Yes go for it please take care of the contribution guidelines and do not forget to add a short video and link of your work.
Happy coding:)
