### ISSUE TITLE
Import Tribute  to Contributors 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [LetsGrowMoreCommunity/WebDev-Playyard#91]
Import tribute to contributors from this project Read the readme file and follow the steps that will help you in getting that you can add the link to tribute to contributors in readme just above the last line 

https://github.com/rohan-kulkarni-25/Tribute-To-Contributors

**Comment by Ruheej1** [comment]
Please assign this to me under LGMSOC'21, I will do it

**Comment by Sanskriti2401** [comment]
@Ruheej1 Yes, you can start working but make sure that your PR will get merged before 11.59 pm today to get counted.
